name: Pull Request on Branch Push
on:
  push:
    branches:
    - main

jobs:
  auto-pull-request:
    name: PullRequestAction
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Install GitHub CLI
      run: |
        sudo apt update
        sudo apt install gh -y

    # - name: Authenticate GitHub CLI
    #   run: gh auth login --with-token ${{ secrets.GITHUB_TOKEN }}

    - name: Create Pull Request
      run: |
        gh pr create --title "Automated PR" --body "This is an automated PR created by GitHub Actions." --base chenYayaya/test-repo --head gloriachen09/test-repo:main
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

